import Head from 'next/head'
import { useRouter } from 'next/router'
import { useContext } from 'react'
import { Context } from '../AppContext'
import withAuth from '../components/HOC/withAuth'
import Todo from '../components/Todo'

const Home = () => {

  const { state: { authDetails: { token } } } = useContext(Context)

    const router = useRouter()
  
  if (!token) {
    router.push('/login')
    return null;
    }

    return (
    <>
      <Head>
        <title>Realtime Todo | Never miss any tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Todo/>   
    </>
  )
}

export default withAuth(Home)
